# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9sAi < Formula
  desc "K9s AI — Kubernetes CLI with built-in AI/Copilot assistant"
  homepage "https://github.com/orshohat1/k9s-ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Darwin_amd64.tar.gz"
      sha256 "48fac59e1fd936b35251c5cf561797fcab956729230722e23fdd5239d863f94d"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Darwin_arm64.tar.gz"
      sha256 "e868e3839c046340cdb3fbd4a914e7588466d49cd3c55f1118054e6befd218c9"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Linux_amd64.tar.gz"
      sha256 "721d24a033431aeaf98d3ab2083269d79285f1b6fe8c5fa22068739bf77bc2b7"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Linux_arm64.tar.gz"
      sha256 "ed5527a585521a7a32b95e0d0e4d33cf02a9f7355cb61cead4c9bf6e65d8e30a"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  test do
    system "#{bin}/k9s-ai", "version"
  end
end
